// Identify possible password spray activity
let knownIPs = dynamic(["8.8.8.8","1.1.2.2"]); 
//let knownIPs = (_GetWatchlist('trustedIP') | project IPAddress);
let pwdSprayActivity = OktaSSO
| where eventType_s =~ "user.session.start" and outcome_reason_s in ("VERIFICATION_ERROR", "INVALID_CREDENTIALS")
// let's get rid of trusted IP space
| where client_ipAddress_s !in (knownIPs)
| project TimeGenerated, outcome_reason_s, actor_alternateId_s, client_ipAddress_s, client_userAgent_rawUserAgent_s ;
pwdSprayActivity